### ISSUE TITLE
stuck on loading 4/11

### ISSUE THREAD

**Issue by MSandro** [alphaqu/DashLoader-Legacy#19]
[15:44:34] [Thread-446/INFO]: [STDOUT]: class juuxel.adorn.block.property.OptionalProperty$Value$Some / Some(value=purple)
[15:44:34] [Thread-446/INFO]: [STDOUT]: class juuxel.adorn.block.property.OptionalProperty$Value$Some / Some(value=cyan)
[15:44:34] [Thread-446/INFO]: [STDOUT]: class juuxel.adorn.block.property.OptionalProperty$Value$Some / Some(value=light_gray)
[15:44:34] [Thread-446/INFO]: [STDOUT]: class juuxel.adorn.block.property.OptionalProperty$Value$Some / Some(value=gray)
[15:44:34] [Thread-446/INFO]: [STDOUT]: class juuxel.adorn.block.property.OptionalProperty$Value$Some / Some(value=pink)
[15:44:34] [Thread-446/INFO]: [STDOUT]: class juuxel.adorn.block.property.OptionalProperty$Value$Some / Some(value=lime)
[15:44:34] [Thread-446/INFO]: [STDOUT]: class juuxel.adorn.block.property.OptionalProperty$Value$Some / Some(value=yellow)
[15:44:34] [Thread-446/INFO]: [STDOUT]: class juuxel.adorn.block.property.OptionalProperty$Value$Some / Some(value=light_blue)
[15:44:34] [Thread-446/INFO]: [STDOUT]: class juuxel.adorn.block.property.OptionalProperty$Value$Some / Some(value=magenta)
[15:44:34] [Thread-446/INFO]: [STDOUT]: class juuxel.adorn.block.property.OptionalProperty$Value$Some / Some(value=orange)
[15:44:34] [Thread-446/INFO]: [STDOUT]: class juuxel.adorn.block.property.OptionalProperty$Value$Some / Some(value=white)
[15:44:34] [Thread-446/INFO]: [STDERR]: java.lang.NullPointerException
[15:44:34] [Thread-446/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.cache.DashRegistry.createSpritePointer(DashRegistry.java:182)
[15:44:34] [Thread-446/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.cache.models.DashBuiltinBakedModel.<init>(DashBuiltinBakedModel.java:40)
[15:44:34] [Thread-446/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.cache.models.factory.DashBuiltInBakedModelFactory.toDash(DashBuiltInBakedModelFactory.java:14)
[15:44:34] [Thread-446/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.cache.DashRegistry.createModelPointer(DashRegistry.java:167)
[15:44:34] [Thread-446/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.cache.models.DashModelData.lambda$new$0(DashModelData.java:42)
[15:44:34] [Thread-446/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.cache.models.DashModelData$$Lambda$11719/904953350.accept(Unknown Source)
[15:44:34] [Thread-446/INFO]: [STDERR]: 	at java.util.HashMap.forEach(HashMap.java:1280)
[15:44:34] [Thread-446/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.cache.models.DashModelData.<init>(DashModelData.java:40)
[15:44:34] [Thread-446/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.DashLoader.saveDashCache(DashLoader.java:231)
[15:44:34] [Thread-446/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.client.DashWindow.lambda$render$0(DashWindow.java:49)
[15:44:34] [Thread-446/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.client.DashWindow$$Lambda$11709/1927531582.run(Unknown Source)
[15:44:34] [Thread-446/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by alphaqu** [comment]
Adorn is unsupported rn.
