### ISSUE TITLE
Freeze on Mapping Blockstates

### ISSUE THREAD

**Issue by ChromaPIE** [alphaqu/DashLoader-Legacy#55]
It **was** all good, but I got the problem now.

```
[14:50:47] [Thread-89/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.size()" because "stateLookup" is null
[14:50:47] [Thread-89/INFO]: [STDERR]: 	at net.oskarstrom.dashloader.data.mappings.DashBlockStateData.<init>(DashBlockStateData.java:27)
[14:50:47] [Thread-89/INFO]: [STDERR]: 	at net.oskarstrom.dashloader.DashMappings.loadVanillaData(DashMappings.java:82)
[14:50:47] [Thread-89/INFO]: [STDERR]: 	at net.oskarstrom.dashloader.DashLoader.saveDashCache(DashLoader.java:169)
[14:50:47] [Thread-89/INFO]: [STDERR]: 	at net.oskarstrom.dashloader.client.DashWindow.lambda$render$0(DashWindow.java:40)
[14:50:47] [Thread-89/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```
Full log: https://pastebin.com/k2yQmDNn

**Comment by alphaqu** [comment]
https://github.com/alphaqu/DashLoader/issues/41

**Comment by ChromaPIE** [comment]
But before this one and only crash DashLoader seemed to be working pretty fine with Sodium and Iris so it's kinda weird.
