### ISSUE TITLE
Crash on game start-up with latest fabric API and mod loader

### ISSUE THREAD

**Issue by ekiplier** [alphaqu/DashLoader-Legacy#60]
So I updated the fabric loader and fabric API and I got a crash. I believe that the versions that used to work for me were 0.11.7 (loader) and fabric API 0.41.3+1.17. Currently running the modpack with the 0.12.5 version of the loader and fabric API 0.43.1+1.17 results in the following crash:

java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'dashloader'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'dashloader'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.oskarstrom.dashloader.client.DashClient failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 5 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [dashloader.mixins.json:accessor.IdentifierAccessor] from phase [DEFAULT] in config [dashloader.mixins.json] from mod [dashloader] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: dashloader.mixins.json:accessor.IdentifierAccessor target net.minecraft.class_2960 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 19 more

**Comment by theRookieCoder** [comment]
These language adapter crashes often occurs when a mod's version isn't set correctly. Did you compile this yourself? If not tell us the DashLoader version you were using

**Comment by theRookieCoder** [comment]
Please send us logs, we can check the warnings and find out what went wrong

**Comment by ekiplier** [comment]
> Please send us logs, we can check the warnings and find out what went wrong

Ok so I was using dashloader-2.0.1 and here's the logs:

[latest.log](https://github.com/alphaqu/DashLoader/files/7608635/latest.log)

**Comment by theRookieCoder** [comment]
This doesn't seem like a problem with DashLoader. Does removing DashLoader cause the game to work properly? If not try Fabric Loader 0.12, there seems to be multiple problems with mixin loading

**Comment by ekiplier** [comment]
You're right! It has to do with sodium actually. Sorry for the inconvenience and thank you! :)

**Comment by theRookieCoder** [comment]
Hope you find a fix for this! You can close this issue

**Comment by alphaqu** [comment]
Hi there! Are you able to try one of our newer 3.0 builds and see if the issue still remains? Currently all of the 3.0 builds are available on our discord.

**Comment by ekiplier** [comment]
I'm a bit busy atm but I might try them later. Thanks :D
