### ISSUE TITLE
Atlas-serialization fails

### ISSUE THREAD

**Issue by UltraBlackLinux** [alphaqu/DashLoader-Legacy#8]
Hey there,
I just changed some resource packs, and the loading bar for "Serializing atlas" is stuck, due to this:
```
[09:28:14] [Thread-167/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "io.activej.serializer.BinarySerializer.encode(io.activej.serializer.BinaryOutput, Object)" because "serializer" is null
[09:28:14] [Thread-167/INFO]: [STDERR]: 	at io.activej.serializer.stream.StreamOutput.serialize(StreamOutput.java:107)
[09:28:14] [Thread-167/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.DashLoader.serializeObject(DashLoader.java:318)
[09:28:14] [Thread-167/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.DashLoader.saveDashCache(DashLoader.java:198)
[09:28:14] [Thread-167/INFO]: [STDERR]: 	at net.quantumfusion.dashloader.client.DashWindow.lambda$render$0(DashWindow.java:43)
[09:28:14] [Thread-167/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:832)

Also please remove this exception from my logs :/
[09:31:50] [dash-manager/INFO]: [STDERR]: java.nio.file.NoSuchFileException: /home/maus/.local/share/multimc/instances/1.16.4_Fusion/.minecraft/config/quantumfusion/dashloader/metadata.activej
```
Are you able to fix this? Is another mod causing this?
Thanks!

**Comment by alphaqu** [comment]
Hey I've noticed a lot of activity on the discord lately about this and i will take a look at it later.

**Comment by alphaqu** [comment]
I've looked at it on my phone and it looks like the recent multithreading of the serializer s are causing the issue

**Comment by alphaqu** [comment]
I believe this issue has been fixed. Please reopen if the issue is still present.
